<template>
<div class="loadingio-spinner-ripple-dk43wgev5n9"><div class="ldio-66dicyg904b">
<div></div><div></div>
</div></div>
</template>

<style scoped>
@keyframes ldio-66dicyg904b {
  0% {
    top: 60px;
    left: 60px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 18px;
    left: 18px;
    width: 78px;
    height: 78px;
    opacity: 0;
  }
}.ldio-66dicyg904b div {
  position: absolute;
  border-width: 4px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-66dicyg904b 3.571428571428571s cubic-bezier(0,0.2,0.8,1) infinite;
}.ldio-66dicyg904b div:nth-child(1) {
  border-color: #d01012;
  animation-delay: 0s;
}
.ldio-66dicyg904b div:nth-child(2) {
  border-color: #f6ec36;
  animation-delay: -1.7857142857142856s;
}
.loadingio-spinner-ripple-dk43wgev5n9 {
  width: 110px;
  height: 110px;
  display: inline-block;
  overflow: hidden;
  background: rgba(NaN, NaN, NaN, 0);
}
.ldio-66dicyg904b {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-66dicyg904b div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>